#!/bin/bash
# /usr/lib/dracut/modules.d/90immutable-ubuntu/immutable-ubuntu-setup.sh
#
# Called by immutable-ubuntu-setup.service (generated by the generator).
# Arguments: $1 = root device spec, $2 = target snapshot subvol name
#
# Workflow:
#   1. Resolve the root device to a /dev path.
#   2. Wait for it to appear (LUKS decryption may still be settling).
#   3. Mount btrfs top-level (subvolid=5).
#   4. Delete the previous @rootfs (and nested subvolumes).
#   5. Create a writable snapshot of the target as @rootfs.
#   6. Fix fstab inside @rootfs.
#   7. Unmount top-level.

set -euo pipefail

ROOT_SPEC="$1"
TARGET="$2"

echo "immutable-ubuntu-setup: root=$ROOT_SPEC target=$TARGET"

# ── Resolve root device ──────────────────────────────────────────────
case "$ROOT_SPEC" in
    UUID=*)  DEV="/dev/disk/by-uuid/${ROOT_SPEC#UUID=}" ;;
    LABEL=*) DEV="/dev/disk/by-label/${ROOT_SPEC#LABEL=}" ;;
    block:*) DEV="${ROOT_SPEC#block:}" ;;
    *)       DEV="$ROOT_SPEC" ;;
esac

# Wait up to 30 seconds for the device
for i in $(seq 1 30); do
    [ -b "$DEV" ] && break
    echo "immutable-ubuntu-setup: waiting for $DEV ($i/30)..."
    sleep 1
done

if [ ! -b "$DEV" ]; then
    echo "immutable-ubuntu-setup: ERROR: device $DEV not found" >&2
    exit 1
fi

# ── Mount btrfs top-level ─────────────────────────────────────────────
TOPLEVEL="/run/immutable-ubuntu-toplevel"
mkdir -p "$TOPLEVEL"

if ! mount -t btrfs -o subvolid=5 "$DEV" "$TOPLEVEL"; then
    echo "immutable-ubuntu-setup: ERROR: cannot mount btrfs top-level" >&2
    exit 1
fi

# shellcheck disable=SC2317  # invoked indirectly via trap
cleanup() {
    umount "$TOPLEVEL" 2>/dev/null || true
}
trap cleanup EXIT

# ── Delete previous @rootfs ───────────────────────────────────────────
ROOTFS="${TOPLEVEL}/@rootfs"
if [ -d "$ROOTFS" ]; then
    echo "immutable-ubuntu-setup: deleting previous @rootfs"
    # Delete nested subvolumes first (bottom-up)
    nested=$(btrfs subvolume list -o "$ROOTFS" 2>/dev/null \
             | awk '{print $NF}' | sort -r) || true
    for sub in $nested; do
        btrfs subvolume delete "${TOPLEVEL}/${sub}" 2>/dev/null || true
    done
    if ! btrfs subvolume delete "$ROOTFS"; then
        echo "immutable-ubuntu-setup: WARNING: failed to delete old @rootfs" >&2
    fi
fi

# ── Create writable snapshot ─────────────────────────────────────────
SNAP="${TOPLEVEL}/${TARGET}"
if [ ! -d "$SNAP" ]; then
    echo "immutable-ubuntu-setup: ERROR: snapshot $TARGET not found" >&2
    exit 1
fi

echo "immutable-ubuntu-setup: creating writable @rootfs from $TARGET"
if ! btrfs subvolume snapshot "$SNAP" "$ROOTFS"; then
    echo "immutable-ubuntu-setup: ERROR: snapshot creation failed" >&2
    exit 1
fi

# ── Fix fstab ─────────────────────────────────────────────────────────
if [ -f "${ROOTFS}/etc/fstab" ]; then
    sed -i 's/subvol=@,/subvol=@rootfs,/' "${ROOTFS}/etc/fstab"
fi

echo "immutable-ubuntu-setup: @rootfs ready"
exit 0
